name: Download File to Repo

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "URL of file to download"
        required: true
        type: string
      output_filename: # اضافه کردن این بخش اختیاری است برای تعیین نام فایل خروجی
        description: "Desired filename for the downloaded file (optional)"
        required: false
        type: string
        default: "downloaded_file"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4 # <<<--- آپدیت شده به v4

      - name: Download file
        run: |
          # استفاده از wget که معمولا پایدارتر است
          # -O: نام فایل خروجی را مشخص می‌کند
          # --no-check-certificate: اگر با خطای SSL مواجه شدی، این گزینه را اضافه کن (احتیاط!)
          # -L: دنبال کردن ریدایرکت‌ها
          wget -L "${{ github.event.inputs.file_url }}" -O "${{ github.event.inputs.output_filename }}"

          # اگر wget کار نکرد، این دستور curl را امتحان کن:
          # curl -L "${{ github.event.inputs.file_url }}" -o "${{ github.event.inputs.output_filename }}"


      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Downloaded file from URL: ${{ github.event.inputs.file_url }}" || echo "No changes to commit"
          git push
