name: Download File to Repo

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "URL of file to download"
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Download file
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full file

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          mv downloaded_file file_from_url
          git add .
          git commit -m "Downloaded file from URL"
          git push
